language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

sudo: required
services:
  - docker

after_success: |
  # coverage
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    docker run --security-opt seccomp=unconfined -v "$PWD:/volume" xd009642/tarpaulin \
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
