[package]
name = "fingertree"
version = "0.1.0"
authors = ["Pavel Aslanov <asl.pavel@gmail.com>"]

[dependencies]

[dev-dependencies]
criterion = "0.2"

[lib]
bench = false

[[bench]]
name = "criterion"
harness = false
